### PR TITLE
Support COSE detached content

### PR DESCRIPTION
**Pull request by kentakayama**
This PR makes t_cose supporting "detached content", mentioned in Issue #33 ,
- introduces new options `T_COSE_OPT_DETACHED_CONTENT` when signing and `T_COSE_OPT_ALLOW_DETACHED_CONTENT` when verifying in the first commit "add: options for detached content"
- adds condition-branch to support "detached content" when signing and verifying, and modifies the rile of  `t_cose_sign1_encode_parameters()` and `t_cose_sign1_encode_signature()` in the second commit "change: support detached content" (see below in detail)
- modifies existing test codes due to the second commit, and adds new test code `short_circuit_self_detached_content_test()` in the third commit "add&change: test for detached content"

Please squash when merging, because 2nd and 3rd commits are inseparable.  

# Changes in logic and interface when signing
Before
```src/t_cose_sign1_sign.c
enum t_cose_err_t t_cose_sign1_encode_parameters(struct t_cose_sign1_sign_ctx *me,
                                                 QCBOREncodeContext           *cbor_encode_ctx)
{
    ...
    QCBOREncode_BstrWrap(cbor_encode_ctx);
}

enum t_cose_err_t t_cose_sign1_encode_signature(struct t_cose_sign1_sign_ctx *me
                                                QCBOREncodeContext           *cbor_encode_ctx)
{
    QCBOREncode_CloseBstrWrap2(cbor_encode_ctx, false, &signed_payload);
    ...
}

enum t_cose_err_t t_cose_sign1_sign()
{
    result = t_cose_sign1_encode_parameters(me, &encode_context);
    QCBOREncode_AddEncoded(&encode_context, payload);
    result = t_cose_sign1_encode_signature(me, &encode_context);
}
```

After
```src/t_cose_sign1_sign.c
enum t_cose_err_t t_cose_sign1_encode_parameters(struct t_cose_sign1_sign_ctx *me,
                                                 QCBOREncodeContext           *cbor_encode_ctx)
{
    ...
    //QCBOREncode_BstrWrap(cbor_encode_ctx); /* moved to t_cose_sign1_sign() */
}

/* caused an !INTERFACE CHANGE! because I moved out the QCBOREncode_CloseBstrWrap2 */
enum t_cose_err_t t_cose_sign1_encode_signature(struct t_cose_sign1_sign_ctx *me
                                                QCBOREncodeContext           *cbor_encode_ctx,
                                                struct q_useful_buf_c         signed_payload) {
    //QCBOREncode_CloseBstrWrap2(cbor_encode_ctx, false, &signed_payload); /* moved to t_cose_sign1_sign() */
    ...
}

enum t_cose_err_t t_cose_sign1_sign() {
    ...
    result = t_cose_sign1_encode_parameters(me, &encode_context);

    if(me->option_flags & T_COSE_OPT_DETACHED_CONTENT) {
        /* add only nil (F6) */
        QCBOREncode_AddNULL(&encode_context);
    } else {
        QCBOREncode_BstrWrap(&encode_context); /* moved from t_cose_sign1_encode_parameters() */
        QCBOREncode_AddEncoded(&encode_context, payload); /* add the target payload */
        QCBOREncode_CloseBstrWrap2(&encode_context, false, &signed_payload); /* moved from t_cose_sign1_encode_signature() */
    }

    /* caused an !INTERFACE CHANGE! because I moved out the QCBOREncode_CloseBstrWrap2 */
    result = t_cose_sign1_encode_signature(me, &encode_context, signed_payload);
    ...
}
```

# Change in logic when vefirying
Before
```src/t_cose_sign1_verify.c
enum t_cose_err_t t_cose_sign1_verify(struct t_cose_sign1_verify_ctx *me,
                                      struct q_useful_buf_c           cose_sign1,
                                      struct q_useful_buf_c          *payload,
                                      struct t_cose_parameters       *returned_parameters)
{
    ...
    /* --- The payload --- */
    QCBORDecode_GetByteString(&decode_context, payload);
    ...
}
```

After
```
enum t_cose_err_t t_cose_sign1_verify(struct t_cose_sign1_verify_ctx *me,
                                      struct q_useful_buf_c           cose_sign1,
                                      struct q_useful_buf_c          *payload,
                                      struct t_cose_parameters       *returned_parameters)
{
    ...
    /* --- The payload --- */
    if(me->option_flags & T_COSE_OPT_ALLOW_DETACHED_CONTENT) {
        QCBORDecode_GetNext(&decode_context, &tmp_payload);
        if(tmp_payload.uDataType == QCBOR_TYPE_NULL) {
            /* "detached content": no need to overwrite the payload */
        } else if (tmp_payload.uDataType == QCBOR_TYPE_BYTE_STRING) {
            /* not "detached content": need to overwrite the payload */
            payload->ptr = tmp_payload.val.string.ptr;
            payload->len = tmp_payload.val.string.len;
        } else {
            /* ERROR! */
        }
    } else {
        QCBORDecode_GetByteString(&decode_context, payload);
    }
    ...
}
```

### CODE REVIEW

**Comment by laurencelundblade** [comment]
Hi Ken,

I'd like the interface to be different than you have it, partly to not break backwards compatibility and partly for design reasons. The interface change and backwards compatibility issue here is actually pretty big. It would require a lot of explaining for the many people that use t_cose now. Also, the new interface has an in/out parameter that doesn't respect const correctly. 

On the encode side, I'd like there to be a new method that looks like this:
enum t_cose_err_t
```
t_cose_sign1_sign_detached(struct t_cose_sign1_sign_ctx *context,
                  struct q_useful_buf_c         detatched_payload,
                  struct q_useful_buf           out_buf,
                  struct q_useful_buf_c        *result);
```

The existing public interface of t_cose_sign1_sign(), t_cose_sign1_encode_parameters() and t_cose_sign1_encode_signature() would be the same. 

Similarly there would be a new method
```
enum t_cose_err_t t_cose_sign1_verify_detatched(struct t_cose_sign1_verify_ctx *context,
                                      struct q_useful_buf_c           sign1,
                                      struct q_useful_buf_c          detached_payload,
                                      struct t_cose_parameters       *parameters);
```

and t_cose_sign1_verify() would be the same and backwards compatible.

T_COSE_OPT_ALLOW_DETACHED_CONTENT would be eliminated.

My first thought on how to implement this would be to rename the some existing functions and make them semi-private interfaces, t_cose_sign1_encode_parameters_internal() and t_cose_sign1_encode_signature_internal() that have an additional parameter or two to control how they behave for regular versus detached content. Then I'd wrap them with inline functions t_cose_sign1_encode_signature() and t_cose_sign1_encode_parameters() that select the non-detached behavior and provide backwards compatibility. t_cose_sign1_sign_detached() would invoke them for detached behavior.  Then do similar for t_cose_sign1_verify().

If you don't want to do this work, I will do it, but it will take me about a week as I have other things I have to work on too. I'd prefer if you did it (since I have other things to do). Thx :-)

In general, thanks for this. I'm happy that t_cose is getting to support detached content.

LL

**Comment by hisanak** [comment]
I agree with you. I've misunderstood that the interfaces that I changed are almost private. Let me try to rewrite the commits. Maybe it takes also several days.  
Thank you for your comments and the great library!

**Comment by laurencelundblade** [comment]
While we are at it, it seems good to add support for AAD which is very similar to detached content and which turns out to be easy to implement. I have a first PR here #35. I used inline implementations for backward compatibility. Will clean it up some and probably merge in the next few days.

So I think one more parameter should be added:
```
t_cose_sign1_sign_detached(struct t_cose_sign1_sign_ctx *context,
                  struct q_useful_buf_c         detatched_payload,
                  struct q_useful_buf_c         aad,
                  struct q_useful_buf           out_buf,
                  struct q_useful_buf_c        *result);
```
Same for verify detached. 

No rush from my side. Let me know if you need something. 

Thanks!

**Comment by hisanak** [comment]
I was too late but now it can sign/verify the COSE binary with detached content.
Due to the conflict between the new functionality AAD, some functions such as `t_cose_sign1_sign()` and `t_cose_sign1_verify()` become ugly, but they remain backward compatible.

Can I improve my implementation?

**Comment by kentakayama** [comment]
I posted 2 comments with another account.
hisanak is my private one :)

**Comment by laurencelundblade** [comment]
I'm working on some comments. Will take a few days. Thanks again!

**Review by laurencelundblade — CHANGES_REQUESTED** [review]
Definitely much closer. Have a few request. Took me a little while to think it through. :-)

Really appreciate the contribution here!  Thank you.

LL

**Pull request merged**
